[PEAUTY-temp8] feat AllReviews & refactor contentGeneral Options
pawfit/pawfit-BE pull request #102
Opened 2024-12-16 12:32 UTC by Shanate

## 📄 [PEAUTY-temp8] feat AllReviews & refactor contentGeneral Options

Jira : [PEAUTY-temp8](url)

## ✨ 변경 사항
- [ ] 기능 추가/변경 설명
- [ ] 버그 수정 설명
- [ ] 문서 수정 설명

리뷰 작성 시 contentGeneral이 단일 선택이 아닌, 복수 선택입니다.
따라서 해당 부분들을 전체적으로 <List>로 감쌌습니다.

+ 추가적으로 상세 조회를 List로 만든 해당 유저의 리뷰 전체 조회 API를 합쳤습니다.

## 📅 작업 일정

- Expected MD: 0.2 MD
- Actual MD: 0.4 MD
### Difference reason (If correct, no need.)
- None.

## ✔️ 확인 사항

- [ ] 코드가 잘 작동하는지 확인했나요?
- [ ] 새로운 기능에 대한 테스트가 추가되었나요?
- [ ] 문서가 업데이트되었나요?

2024-12-16 12:50 UTC, harvartz approved these changes
LGTM 👍

2024-12-16 14:41 UTC, weejinyoung requested changes
이번에도 네이밍 관련 변경 요청입니당

2024-12-16 14:41 UTC, weejinyoung commented on peauty-domain/src/main/java/com/peauty/domain/review/Review.java
>      @Getter private List<ReviewImage> reviewImages;     // 리뷰이미지
복수명사 please 네이밍 조금만 더 신경써봐요 우리
as is: contentGeneral
to be: contentGenerals

2024-12-17 03:00 UTC, weejinyoung approved these changes
LGTM

2024-12-17 08:30 UTC, harvartz approved these changes
LGTM 👍

2024-12-17 08:30 UTC, harvartz commented on peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewRepository.java
> +    """)
많은 조인이 어떤 성능에 영향을 미칠지 나중에 생각해봐요 👍

2024-12-17 08:40 UTC, weejinyoung approved these changes
LGTM

2024-12-17 08:40 UTC, weejinyoung commented on peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewService.java
> +    GetUserReviewsResult getUserReviews(Long userId);
User -> Customer

2024-12-17 08:40 UTC, weejinyoung commented on peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewServiceImpl.java
> +
estimateCost -> desiredCost

2024-12-17 08:45 UTC, merged