[Peauty-81] Create Domain & Entity about Review
pawfit/pawfit-BE pull request #25
Opened 2024-11-30 06:42 UTC by Shanate

## 📄 [Peauty-81] Create Domain & Entity about Review

Jira : [PEAUTY-81](https://multicampusuplus.atlassian.net/browse/PEAUTY-81?atlOrigin=eyJpIjoiNjA4OWNiM2M4ODc5NDM2MDkzMWM4NmYxMDAzOWYxNWUiLCJwIjoiaiJ9)

## ✨ 변경 사항
- [ ] 기능 추가/변경 설명
- [ ] 버그 수정 설명
- [ ] 문서 수정 설명

리뷰에 관한 도메인과 엔티티입니다.
리뷰 이미지는 단건이 아닌 최대 3건을 받을 수 있도록 되어 있기 때문에,
기존 ERD를 수정했습니다.
리뷰 평점에 관해서는 기존 float로 Review 테이블에 있었으나 Enum을 사용해 0부터 5까지 0.5로 받을 수 있도록 변경했습니다.
수정 전 : Review 테이블에 이미지 URL가 있는 방식.
수정 후 : Review 테이블과 ReviewImage 테이블을 1:N 관계로 설정.

## 📅 작업 일정

- Expected MD: 0.2 MD
- Actual MD: 0.2 MD
### Difference reason (If correct, no need.)
- None.

## ✔️ 확인 사항

- [ ] 코드가 잘 작동하는지 확인했나요?
- [ ] 새로운 기능에 대한 테스트가 추가되었나요?
- [ ] 문서가 업데이트되었나요?

2024-11-30 11:57 UTC, harvartz approved these changes
Rating 네이밍만 다르게 하면 어떨 까 생각이 듭니다!

2024-11-30 11:57 UTC, harvartz commented on peauty-domain/src/main/java/com/peauty/domain/review/Rating.java
> +public enum Rating {
Rating이라는 클래스 이름이 있어서 조금 헷갈릴 수 있을 것 같기도 하네요.. 물론 앞에 클래스이냐 enum 차이는 있지만 다른 네이밍이면 생각할 필요 없지 않을까 싶습니다

2024-12-01 11:03 UTC, weejinyoung requested changes
고생하셨습니당 점점 속도가 올라오시네요 👍 
네이밍 관련 리뷰 하나 달았습니당
변경 요청 확인해주세욥 🙇

2024-12-01 11:03 UTC, weejinyoung commented on peauty-domain/src/main/java/com/peauty/domain/puppy/Puppy.java
> +    private List<AddyImage> addyImageUrl;       // Addy URL
AddyImage 의 리스트라면 변수 이름도 AddyImages
이렇게 가져가는 게 좋지 않을까욤

2024-12-01 11:35 UTC, Shanate commented on peauty-domain/src/main/java/com/peauty/domain/puppy/Puppy.java
> +    private List<AddyImage> addyImageUrl;       // Addy URL
List<AddyImage> addyImageUrl이 아닌 List<AddyImages> addyImageUrl이 좀 더 명확한 변수 이름이라는 것일까요?

2024-12-01 11:37 UTC, Shanate commented on peauty-domain/src/main/java/com/peauty/domain/review/Rating.java
> +public enum Rating {
해당 부분은 지난번에도 한 번 소리를 들었어서, service를 뺀 네이밍으로 변경한 것이었는데 클래스와 enum에 대해서도 겹치는 거 보면서 좀 아니다 싶긴 했습니다. 해당 부분은 reviewRating or startRating이라는 이름을 생각해 두긴 했었는데, 혹시 더 괜찮은 이름있으시다면 추천해주셔도 좋을거같습니다.

2024-12-01 12:54 UTC, weejinyoung requested changes

2024-12-01 12:54 UTC, weejinyoung commented on peauty-domain/src/main/java/com/peauty/domain/review/Review.java
> +    private List<String> reviewImageUrl;        // 리뷰이미지
바뀐 ERD 에 맞게 변경해주세욤!

2024-12-01 13:24 UTC, Shanate commented on peauty-domain/src/main/java/com/peauty/domain/review/Review.java
> +    private List<String> reviewImageUrl;        // 리뷰이미지
ERD에 맞춰서 업데이트하도록 하겠습니다.

2024-12-02 07:16 UTC, weejinyoung approved these changes
LGTM 👍

2024-12-02 07:46 UTC, merged