[PEAUTY-95] Adding Rating, Badges about GetAroundWorkspace API
pawfit/pawfit-BE pull request #45
Opened 2024-12-05 13:28 UTC by Shanate

## 📄 [PEAUTY-95] Adding Rating, Badges about GetAroundWorkspace API

Jira : [PEAUTY-95](https://multicampusuplus.atlassian.net/browse/PEAUTY-95?atlOrigin=eyJpIjoiMjA2ZTMyOTlhOWE3NGZhZmEyYmRjNWE2MmQwNGE3M2YiLCJwIjoiaiJ9)

## ✨ 변경 사항
- [ ] 기능 추가/변경 설명
- [ ] 버그 수정 설명
- [ ] 문서 수정 설명

기존 주변 디자이너 조회 API를 프론트 요구 화면에 맞게 수정했습니다. 기존에 받아오는 정보는 그대로인 채로, 해당 미용실을 가진 디자이너의 대표뱃지와 해당 미용실의 시저 등급을 조회합니다.

## 📅 작업 일정

- Expected MD: 0.2 MD
- Actual MD: 0.6 MD
### Difference reason (If correct, no need.)
- None.

## ✔️ 확인 사항

- [ ] 코드가 잘 작동하는지 확인했나요?
- [ ] 새로운 기능에 대한 테스트가 추가되었나요?
- [ ] 문서가 업데이트되었나요?

2024-12-05 13:32 UTC, Shanate commented
하

2024-12-05 15:54 UTC, harvartz approved these changes
코드에 대해서 리뷰 남겨두었습니다! 확인 부탁드립니다 : )

2024-12-05 15:54 UTC, harvartz commented on peauty-customer-api/src/main/java/com/peauty/customer/business/customer/dto/GetAroundWorkspaceResult.java
> +/*  TODO
TODO 주석이 화려하네요.. : )

2024-12-05 15:54 UTC, harvartz commented on peauty-customer-api/src/main/java/com/peauty/customer/business/customer/CustomerServiceImpl.java
> +                    List<String> representativeBadges = workspacePort.getBadges(designer.getDesignerId())
워크 스페이스 도메인을 살펴보시면 워크 스페이스안에는 뱃지가 없는 걸로 알고 있습니다.
뱃지는 디자인 도메인 안에 있죠, 그런데 위의 코드에서는 뱃지를 가져오기 위해 workspacePort를 사용하는 부분이
조금 어색하지 않나.., 생각이 듭니다! 

뱃지라는 개념은 워크스페이스 보다는 디자이너에 있는게 더 적합하다는 생각에 디자인 도메인 안에 포함시키게 했습니다! 그래서 getBadges라는 메서드도 workspacePort가 아니라 designerPort에 넣어둔 것이구요!

이 의견에 대한 재혁님의 생각이 궁금합니다 👍

2024-12-06 01:20 UTC, weejinyoung requested changes
현재 미용사의 대표뱃지만 조회하는 기능이 구현되어있는 것으로 보여집니다
미용사가 소지하고있는 모든 뱃지를 조회하는 기능이 필요해보여요!

2024-12-06 01:20 UTC, weejinyoung commented on peauty-customer-api/src/main/java/com/peauty/customer/implementaion/designer/DesignerAdapter.java
> +
대표뱃지를 조회하는 메소드의 이름은 getRepresentativeBadges 이여야 하지 않나 싶습니다!
getBadges 는 디자이너가 가지고있는 모든 뱃지를 가지고오는 의미로 해석돼요

2024-12-06 04:43 UTC, weejinyoung commented on peauty-customer-api/src/main/java/com/peauty/customer/implementaion/designer/DesignerAdapter.java
> +
다른 테스트에서 이어 진행

2024-12-06 04:43 UTC, merged