[PEAUTY-170] Impl Review Rating & Review Count Logic
pawfit/pawfit-BE pull request #71
Opened 2024-12-10 12:45 UTC by Shanate

## 📄 [PEAUTY-170] Impl Review Rating & Review Count Logic

Jira : [PEAUTY-170](https://multicampusuplus.atlassian.net/browse/PEAUTY-170?atlOrigin=eyJpIjoiNGQwZjJhYTU2NDUyNDZmNGJlNTNiNTAzMDJhMDkxNWEiLCJwIjoiaiJ9)

## ✨ 변경 사항
- [ ] 기능 추가/변경 설명
- [ ] 버그 수정 설명
- [ ] 문서 수정 설명

기존 리뷰 작성, 수정, 삭제에 없던 로직을 추가했습니다.
해당 로직은 리뷰를 했을 시에 따른 갯수 카운트와 평점 계산입니다.
사족 : 해당 로직은 하나의 업데이트로 관리할 수가 있을거 같았는데 그랬을 경우, 리뷰 갯수를 계속해서 증가하는 문제가 생겨 각각을 따로 만들었습니다.

## 📅 작업 일정

- Expected MD:  0.5 MD
- Actual MD: 0.8 MD
### Difference reason (If correct, no need.)
- None.

## ✔️ 확인 사항

- [ ] 코드가 잘 작동하는지 확인했나요?
- [ ] 새로운 기능에 대한 테스트가 추가되었나요?
- [ ] 문서가 업데이트되었나요?

2024-12-10 14:50 UTC, weejinyoung requested changes
흠... 네이밍 관련 리뷰가 또 달렸습니다.. 다음엔 꼭꼭 더블체크해주세요
그리고 워크스페이스의 별점 총 갯수와 평점 평균 업데이트 로직이 워크스페이스에 있네요
이건 아주 좋은 판단이라고 생각합니다
다만 도메인에 중요한 비즈니스 로직을 추가할 땐 테스트 코드를 꼭 작성해주세요
어렵지 않을 테니 네이밍 수정과 워크스페이스 리뷰 반영 테스트 코드 작성 부탁드릴게요!

2024-12-10 14:50 UTC, weejinyoung commented on peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/WorkspacePort.java
> +    Workspace DeleteReviewStats(Long designerId, ReviewRating deletedRating);
부디 피알 올리기 전에 더블 체크 부탁드리겠습니다... 진짜 네이밍 테크 세미나를 해야할 것 같아요

2024-12-10 14:50 UTC, weejinyoung commented on peauty-domain/src/main/java/com/peauty/domain/response/PeautyResponseCode.java
이 예외도 조금 더 자세한 상황을 표현해주세요
무엇이 어떻게 잘못된 리뷰 업데이트인지

2024-12-10 15:10 UTC, Shanate commented on peauty-domain/src/main/java/com/peauty/domain/response/PeautyResponseCode.java
리뷰카운트가 현재 0인 상황에서 업데이트 혹은 제거하려는 접근이기 때문에, "현재 리뷰가 존재하지 않아 수정할 수 없습니다."라는 메시지를 띄울 수 있도록 하겠습니다. message 또한 "No Review, Invalid Review Update"로 수정하겠습니다.

2024-12-10 15:13 UTC, Shanate commented on peauty-customer-api/src/main/java/com/peauty/customer/business/workspace/WorkspacePort.java
> +    Workspace DeleteReviewStats(Long designerId, ReviewRating deletedRating);
빠르게 조치하도록 하겠습니다.

2024-12-11 02:03 UTC, harvartz approved these changes
고생하셨습니다!

2024-12-11 02:03 UTC, harvartz commented on peauty-domain/src/main/java/com/peauty/domain/designer/Workspace.java
> +
동시성 문제.. 맛있는 소재네요 어떻게 해결하실지 궁금해집니다 : )

2024-12-11 02:35 UTC, Shanate commented on peauty-domain/src/main/java/com/peauty/domain/designer/Workspace.java
> +
우선은 완성이 목표라 해당 문제는 후순위로 두기로 했습니다.

2024-12-11 11:08 UTC, merged