[PEAUTY-210] Add Logic for Process and Thread State Changes on Payment Completion
pawfit/pawfit-BE pull request #80
Opened 2024-12-12 08:16 UTC by harvartz

## 📄 [PF-210] Add Logic for Process and Thread State Changes on Payment Completion

Jira : [PEAUTY-210](https://multicampusuplus.atlassian.net/browse/PEAUTY-210?atlOrigin=eyJpIjoiNmY0YjllNTUyNDExNDdmMTg0ZmE1MTUwYTQ0MGQ1ZTEiLCJwIjoiaiJ9)

## ✨ 변경 사항
- [x] 기능 추가/변경 설명
- [x] 버그 수정 설명
- [x] 문서 수정 설명

- 견적서 수락 시, 기존에는 API를 사용하여 프로세스, 쓰레드 상태 변화를 직접 진행했습니다.
- 지금은 결제기능이 있어서 결제가 유효성 검증을 통해 정상적으로 진행되었을 때, 프로세스와 쓰레드 상태 변화를 진행하게 로직을 추가했습니다.

## 📅 작업 일정

- Expected MD: 0.3MD
- Actual MD: 0.3MD
### Difference reason (If correct, no need.)
- None.

## ✔️ 확인 사항

- [x] 코드가 잘 작동하는지 확인했나요?
- [x] 새로운 기능에 대한 테스트가 추가되었나요?
- [x] 문서가 업데이트되었나요?

2024-12-12 10:22 UTC, Shanate approved these changes
수고하셨습니다 👍

2024-12-12 10:22 UTC, Shanate commented on peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/CustomerController.java
> -
주석 지운것 좋습니다.

2024-12-13 03:35 UTC, weejinyoung requested changes
고생하셨습니당 
중요한 로직 관련 리뷰가 포함됐어요 확인 부탁드려요!

2024-12-13 03:35 UTC, weejinyoung commented on peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/bidding/CustomerBiddingController.java
> +//    }
감사합니당

2024-12-13 03:35 UTC, weejinyoung commented on peauty-customer-api/src/main/java/com/peauty/customer/presentation/controller/customer/CustomerController.java
> -
청소 감사합니당

2024-12-13 03:35 UTC, weejinyoung commented on peauty-domain/src/main/java/com/peauty/domain/payment/Order.java
> +    }
이거 어떤 메소드인지 감이 잘 오지 않아욤
update 라는 추상적인 네이밍보단 더 자세한 네이밍 혹시 있을까요?

2024-12-13 03:35 UTC, weejinyoung commented on peauty-payment/src/main/java/com/peauty/payment/business/PaymentServiceImpl.java
>                  iamportClient.cancelPaymentByImpUid(new CancelData(iamportResponse.getImpUid()
스레드의 취소란 고객과 디자이너 간의 입찰 관계가 끝나버리는 것인데 결제 검증에 실패했다고 입찰 관계가 끝나진 않을 것입니다
결제 검증에 실패하면 예외를 던져서 트랜잭션을 롤백하는 정도가 맞을 것 같아요!

2024-12-13 05:03 UTC, harvartz commented on peauty-domain/src/main/java/com/peauty/domain/payment/Order.java
> +    }
해당 메서드는 유효성 검증이 끝나고 나서 진행할 메서드라 updateValidatedPayment()로 수정했습니다!

2024-12-14 12:49 UTC, Shanate approved these changes
LGTM

2024-12-15 11:43 UTC, weejinyoung approved these changes
어려운 도메인이라 명확하게 이해는 안되지만... 석진 님의 결제 로직 세미나를 다시 한 번 기대하겠습니다 고생 많으셨습니다

2024-12-15 11:43 UTC, weejinyoung commented on peauty-payment/src/main/java/com/peauty/payment/business/PaymentServiceImpl.java
>              }
예외가 없어졌네요! 감사합니다

2024-12-15 11:46 UTC, merged