[PEAUTY-60] Create domain of relating to Puppy
pawfit/pawfit-BE pull request #9
Opened 2024-11-22 06:04 UTC by Shanate

## 📄 PEAUTY-60 Create domain of relating to Puppy

Jira : [PEAUTY-60](https://sieoneve-1730081705655.atlassian.net/browse/PEAUTY-60?atlOrigin=eyJpIjoiZDEyMGFjNmMxYWVhNDVmNmI5MzRjYjk1MjIwNjUxMzgiLCJwIjoiaiJ9)

## ✨ 변경 사항
- [ ] 반려견 관련 도메인 추가

Puppy, Sex, Image 도메인을 추가했습니다.

## 📅 작업 일정

- Expected MD: 1 MD
- Actual MD: 1 MD
### Difference reason (If correct, no need.)
- None.

## ✔️ 확인 사항

- [ ] 코드가 잘 작동하는지 확인했나요?
- [ ] 새로운 기능에 대한 테스트가 추가되었나요?
- [ ] 문서가 업데이트되었나요?

2024-11-22 06:43 UTC, harvartz approved these changes
다시 리뷰하겠습니다 : )

2024-11-22 06:43 UTC, harvartz commented on peauty-domain/src/main/java/com/peauty/domain/addy/Addy.java
> +    private Long AddyId;            // Addy ID
대...문자 쿨럭 쿨럭..

2024-11-22 06:43 UTC, harvartz commented on peauty-domain/src/main/java/com/peauty/domain/puppy/Breed.java
> +    AustralianShepherd,
이렇게 표현하는 것 말고 다른 식의 enum 표현 방법을 찾아보는 것도 좋을 것 같아요!

2024-11-23 02:49 UTC, Shanate commented on peauty-domain/src/main/java/com/peauty/domain/puppy/Breed.java
> +    AustralianShepherd,
기다려주세요 곧 끝납니다

2024-11-23 04:58 UTC, weejinyoung requested changes
Enum 에 대해 학습을 열심히 하신 게 보이네욥 고생하셨습니다!
몇 가지 변경 요청 남겨요 확인 부탁드립니다 🙇

2024-11-23 04:58 UTC, weejinyoung commented on peauty-domain/src/main/java/com/peauty/domain/puppy/Disease.java
> +    Parasites("Parasites");
Breed 에선 스네이크 케이스 + 대문자로 enum 을 만드셨던데 ex) SAINT_BERNARD
Disease 에선 파스칼 케이스로 만드신 이유가 따로 있으신가욤 ex) CanineDistemper

2024-11-23 04:58 UTC, weejinyoung commented on peauty-domain/src/main/java/com/peauty/domain/puppy/Breed.java
> +    }
`IllegalArgumentException` 가 발생되면 `PeautyCustomerExceptionHandler.handleUncheckedException` 메소드에 걸려서 클라이언트에게 `INTERNAL_SERVER_ERROR` 가 응답될 것입니다
이는 존재하지 않는 견종이 입력된 것은 클라이언트가 알아야 할 예외라고 생각돼요 하지만 `INTERNAL_SERVER_ERROR` 가 응답되면 클라이언트는 서버의 문제라고밖에 생각하지 못하게 될 것입니다.
그래서 다음과 같이 변경을 추천합니다.

as is: `IllegalArgumentException("존재하지 않는 견종입니다. 다시 입력해주세요.");`
to be: `PeautyException(PeautyResponseCode.NOT_EXITS_BREED);`

자세한 사항은 `PeautyCustomerExceptionHandler` 를 확인하시면 되고 그래도 헷갈리시는 부분이 있다면 구두설명 드리겠습니당 필요 시 말씀해주세요

2024-11-23 04:58 UTC, weejinyoung commented on peauty-domain/src/main/java/com/peauty/domain/puppy/Disease.java
> +                .orElseThrow(() -> new IllegalArgumentException("없는 병명입니다."));
여기에도 위에서 말씀드렸던 예외처리 관련과 같은 맥락입니다!

2024-11-23 04:58 UTC, weejinyoung commented on peauty-domain/src/main/java/com/peauty/domain/addy/Addy.java
> +
이거 AddyImage 가 조금 더 맞는 네이밍이지 않을까욤

2024-11-23 04:58 UTC, weejinyoung commented on peauty-domain/src/main/java/com/peauty/domain/puppy/Sex.java
> +}
혹시 요 enum 클래스도 Breed 처럼 맛있게 만들어주실 수 있을까욤
만약에 enum 클래스가 더 많아진다면 추상 클래스나 인터페이스 도입도 고려해볼 수 있을 것 같아요

2024-11-23 08:29 UTC, Shanate commented on peauty-domain/src/main/java/com/peauty/domain/puppy/Disease.java
> +    Parasites("Parasites");
글자 수가 길었던 견종에 비해 짧은 편이었어서 파스칼 케이스로 작성했습니다. 해당 병명은 Breed에서와 같이 통일하도록 하겠습니다.

2024-11-23 10:36 UTC, Shanate commented on peauty-domain/src/main/java/com/peauty/domain/addy/Addy.java
> +    private Long AddyId;            // Addy ID
addyImageUrl로 수정했습니다

2024-11-23 10:37 UTC, Shanate commented on peauty-domain/src/main/java/com/peauty/domain/puppy/Breed.java
> +    }
Exception를 중요시하지 않았었는데, 왜 문제가 되는지 그리고 어떤 방식으로 변경해야하는지 솔루션 감사합니다. 해당 부분 리뷰와 같이 수정 완료했습니다.

2024-11-23 10:37 UTC, Shanate commented on peauty-domain/src/main/java/com/peauty/domain/puppy/Disease.java
> +                .orElseThrow(() -> new IllegalArgumentException("없는 병명입니다."));
해당 부분 또한 수정했습니다.

2024-11-23 10:37 UTC, Shanate commented on peauty-domain/src/main/java/com/peauty/domain/addy/Addy.java
> +
클래스 이름 수정했습니다.

2024-11-23 10:38 UTC, Shanate commented on peauty-domain/src/main/java/com/peauty/domain/puppy/Sex.java
> +}
해당 부분 또한 다른 Enum 클래스와 같은 양식으로 수정했습니다.
공통적으로 흘러가는 Exception를 묶어 인터페이스로 만들 수는 있을 것 같은데 해당 사항 고려해보겠습니다.

2024-11-24 01:12 UTC, weejinyoung approved these changes
리뷰 반영 감사합니다!

2024-11-24 01:15 UTC, harvartz commented on peauty-domain/src/main/java/com/peauty/domain/puppy/Breed.java
> +    }
예전 프로젝트에서는 저도 @Shanate 처럼 했었는데 클라이언트 에러, 서버 에러 이렇게 공통 에러처리가 되어있는지 확인을 못했네요 저도 참고하고 갑니다!

2024-11-24 01:17 UTC, harvartz reviewed
ENUM과 공통 예외에 대해서 이번 리뷰를 통해서 다시 한번 알고 가게 되네요 : )
LGTM 👍

2024-11-24 01:17 UTC, harvartz commented on peauty-domain/src/main/java/com/peauty/domain/puppy/Breed.java
enum 타입에 대한 세미나 기대하고 있겠습니다.. : )

2024-11-24 01:18 UTC, merged

2024-11-24 01:22 UTC, Shanate commented
> 리뷰 반영 감사합니다!
🎉

2024-11-24 01:23 UTC, Shanate commented
> ENUM과 공통 예외에 대해서 이번 리뷰를 통해서 다시 한번 알고 가게 되네요 : ) LGTM 👍

╰(*°▽°*)╯