[PEAUTY-temp2] Impl Get Designer's Reviews
pawfit/pawfit-BE pull request #93
Opened 2024-12-15 06:54 UTC by Shanate

## 📄 [PEAUTY-temp2] Impl Get Designer's Reviews

Jira : [PEAUTY-temp2]

## ✨ 변경 사항
- [ ] 기능 추가/변경 설명
- [ ] 버그 수정 설명
- [ ] 문서 수정 설명

디자이너의 리뷰를 전체 조회하는 API입니다.

estimate proposal에서의 미용 타입과 고객의 닉네임을 가져오는 것에 답이 없어서, 양석진 님이 설명해주신 플로우 참고를 많이 했습니다.

제 의지가 들어간 코드가 아니여서 추후 리팩토링이 많이 들어가야 하는 부분일 것 같습니다.

## 📅 작업 일정

- Expected MD: 1 MD
- Actual MD: 2 MD
### Difference reason (If correct, no need.)
- None.

## ✔️ 확인 사항

- [ ] 코드가 잘 작동하는지 확인했나요?
- [ ] 새로운 기능에 대한 테스트가 추가되었나요?
- [ ] 문서가 업데이트되었나요?

2024-12-15 07:33 UTC, weejinyoung reviewed
고생하셨습니당 몇 가지 궁금한 점 남겨욧

2024-12-15 07:33 UTC, weejinyoung commented on peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewServiceImpl.java
> +    public GetDesignerReviewsResult getDesignerReviews(Long designerId) {
이미 클래스 단에 트랜잭션 어노테이션이 달려있어요!

2024-12-15 07:33 UTC, weejinyoung commented on peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/GetDesignerReviewsResult.java
> +            String totalGroomingFaceType,
`totalGroomingBodyType` 과 `totalGroomingFaceType` 은 전체미용일 때에만 데이터가 존재하는 것으로 알고있어요
만약 위생미용이면 `totalGroomingBodyType` 과 `totalGroomingFaceType` 은 null 일 것입니다
해당 사항이 인지된 코드인 것일까요?!

2024-12-15 07:33 UTC, weejinyoung commented on peauty-customer-api/src/main/java/com/peauty/customer/implementaion/review/ReviewAdapter.java
> +                        .orElseThrow(() -> new PeautyException(PeautyResponseCode.NOT_FOUND_REVIEW));
만약 해당 스레드에 리뷰가 달리지 않았다면 예외 상황인 것인가요?
무조건 리뷰가 달렸을 것이라는 가정 하에 호출되는 메소드일까요

2024-12-15 07:33 UTC, weejinyoung commented on peauty-domain/src/main/java/com/peauty/domain/review/Review.java
> +    @Getter private final String totalGroomingFaceType;
이건 리뷰 테이블엔 없는 필드네요!
혹시 어떤 이유로 리뷰 테이블엔 없는 컬럼이 도메인 객체 모델의 필드엔 존재하게 된 것일까요?

2024-12-15 07:37 UTC, Shanate commented on peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewServiceImpl.java
> +    public GetDesignerReviewsResult getDesignerReviews(Long designerId) {
해당 부분 삭제하도록 하겠습니다.

2024-12-15 07:58 UTC, Shanate commented on peauty-customer-api/src/main/java/com/peauty/customer/implementaion/review/ReviewAdapter.java
> +                        .orElseThrow(() -> new PeautyException(PeautyResponseCode.NOT_FOUND_REVIEW));
예외로 두면 에러가 발생하는데 인지하지 못했습니다. 해당 부분 수정하도록 하겠습니다.

2024-12-15 08:38 UTC, harvartz approved these changes
고생하셨습니다! 진영님 리뷰에 저도 추가적으로 의견 남겨놓았으니 확인해주시면 좋을 것 같아요 👍

2024-12-15 08:38 UTC, harvartz commented on peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewServiceImpl.java
> +    public GetDesignerReviewsResult getDesignerReviews(Long designerId) {
@Shanate @Trancational(readOnly = true), @Transactional의 차이점과 언제 어디에서 주로 다는지 확인해보시는 것도 좋을 것 같습니다 👍

2024-12-15 08:38 UTC, harvartz commented on peauty-domain/src/main/java/com/peauty/domain/review/Review.java
> +    @Getter private final String totalGroomingFaceType;
아마 화면에 위의 타입들이 나와서 같이 넣어두신게 아닌가 추측이 됩니다! 저 필드들도 도메인에 들어가는게 좋을지 아닐지는 판단이 잘 서지는 않지만, 넣게 된다면 네이밍을 바꾸는게 좋지 않을까 생각이 드네요 : )
customerNickname -> reviewerName과 같이 리뷰에 적절한 네이밍을 해주면 좋을 것 같네요

혹은 저 필드들이 리뷰 도메인에 필요가 없다면 dto에 넣어서 처리하는게 어떨까 합니다.
@weejinyoung 이 의견에 대해서 어떤 생각을 가지고 계시는지 궁금하네요 ❓

2024-12-15 08:38 UTC, harvartz commented on peauty-persistence/src/main/java/com/peauty/persistence/bidding/estimate/EstimateProposalRepository.java
> +    List<EstimateProposalEntity> findByProcessIdIn(Collection<Long> processIds);
이건 무엇을 찾는 메서드인가요? processId로 찾는데 In? 이 어떤 뜻인지 모르겠습니다

2024-12-15 08:38 UTC, harvartz commented on peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/GetDesignerReviewsResult.java
> +            String totalGroomingFaceType,
날카롭다..

2024-12-15 08:38 UTC, harvartz commented on peauty-customer-api/src/main/java/com/peauty/customer/implementaion/review/ReviewAdapter.java
> +                Optional<ReviewEntity> reviewEntityOpt = reviewRepository.findByBiddingThreadId(thread.getId());
Opt가 Optional에 해당하는건가요? 저희 네이밍은 약어 쓰지 않고 왠만하면 모두 풀어서 쓰는걸로 가기로 해서 풀어쓰시는게 좋을거 같아요. 하지만 이전에 optional이라는 단어를 네이밍으로 하는게 맞는지 한번 생각해보면 좋을 것 같습니다 🛩️

2024-12-15 12:12 UTC, Shanate commented on peauty-persistence/src/main/java/com/peauty/persistence/bidding/estimate/EstimateProposalRepository.java
> +    List<EstimateProposalEntity> findByProcessIdIn(Collection<Long> processIds);
여러 processId로 EstimateProposalEntity를 조회하게끔합니다. 여러 번 조회를 개별적으로 실행하는 것보다 빠르다고는 합니다.
쿼리 문으로 따지면 where 절에 있는 IN (1,2,3,...) 역할을 한다고 합니다.

2024-12-15 12:12 UTC, Shanate commented on peauty-customer-api/src/main/java/com/peauty/customer/implementaion/review/ReviewAdapter.java
> +                Optional<ReviewEntity> reviewEntityOpt = reviewRepository.findByBiddingThreadId(thread.getId());
해당 부분 수정하도록 하겠습니다.

2024-12-15 12:20 UTC, weejinyoung commented on peauty-domain/src/main/java/com/peauty/domain/review/Review.java
> +    @Getter private final String totalGroomingFaceType;
`reviewerNickname` 필드가 `Review` 클래스에 포함되는 것은 크게 어색하지 않으나 `totalGroomingBodyType` 와 `totalGroomingFaceType` 은 `Review` 클래스의 역할에 어울리지 않는 필드라고 생각해요
"리뷰의 리뷰어닉네임" 이 표현은 어색하지 않으나 "리뷰의 전체미용바디타입", "리뷰의 전체미용얼굴타입"  은 어색한 표현이 되는 것처럼요 

만약 이름을 바꿔서 "진행했던 미용의 전체미용바디타입" 이 된다면 크게 어색하지 않을 순 있으나
이미 견적 제안서나 견적서 클래스가 해당 필드를 가지고 있고 도메인 클래스는 모든 모듈이 영향을 받기 때문에 변경에 있어 조심스러워야 하기 때문에 단순히 화면에 보여지는 것을 위해 해당 필드를 추가하는 건 합당한 명분이라고 보기 어렵다고 생각해요 
그래서 저도 따로 필드를 추가하지 않고 최대한 다른 모듈에 영향을 주지 않기 위해 `Profile` 이란 내부 클래스를 따로 만들었던 것이구요

또한 저 필드에 null 이 아닌 실제 데이터가 있으려면 Review 클래스의 인스턴스를 만들 때 EstimatePropoesl 테이블을 조회해야 할 것입니다 그렇지 않다면 해당 필드에 null 이 들어갈 것이고 이 필드의 게터가 무분별하게 호출된다면 npe 의 위험성이 높아지게 될 것입니다

등등 이것 말고도 여러 이유가 있지만.. 일단 당면 과제인 성공적인 시연을 위해선 구현에 집중해야할 때이니 TODO 로 리팩토링 계획을 명시해주세욥 우리 우리 같이 더 고민해보아요

2024-12-15 12:55 UTC, harvartz commented on peauty-domain/src/main/java/com/peauty/domain/review/Review.java
> +    @Getter private final String totalGroomingFaceType;
최대한 다른 모듈에 영향을 주지 않기 위해 내부 클래스를 만든다는 말이 와닿는 예제인거 같네요! 
이부분은 나중에 꼭 😃  한번 다시 얘기해보면 좋을 것 같습니다 👍

2024-12-15 12:58 UTC, Shanate commented on peauty-domain/src/main/java/com/peauty/domain/review/Review.java
> +    @Getter private final String totalGroomingFaceType;
디자이너에게 달린 리뷰 전체 조회 API가 초반에 전혀 감이 안잡혀서 gpt를 통해 만들었더니 이 사단이 난거같습니다. 리뷰 부분들이 테이블을 타고타고 들어가는게 저에게 좀 난해했던 부분인데, 전체적으로 리팩토링을 빡세게 들어가야할거같습니다...

2024-12-15 13:10 UTC, weejinyoung commented on peauty-customer-api/src/main/java/com/peauty/customer/business/review/ReviewServiceImpl.java
> +    public GetDesignerReviewsResult getDesignerReviews(Long designerId) {
테크 세미나 준비 +1

2024-12-15 13:25 UTC, weejinyoung requested changes
하핫 변경 요청입니다
주말에도 고생이 많으십니다 분명 지금 고생이 다 자산이 될 거에요

2024-12-15 13:25 UTC, weejinyoung commented on peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/GetDesignerReviewsResult.java
> +            String content
앗 근데 이거 지금 봤는데 혹시 리뷰 id 를 안 넣어주신 이유가 있으신가욤
해당 API 의 응답을 보여주는 화면에서 다른 API 요청을 하는 것을 대비하기 위해서 저는 보통 응답 바디에 id 는 다 넣어주는 편입니다
일단 지금 피그마 상에선 필요없어 보이긴 하는데 앵간하면 id 는 응답 바디에 넣어주는 거 추천드려요

2024-12-15 13:25 UTC, weejinyoung commented on peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewMapper.java
> +                : null;
제가 만들었던 getSimpleGroomingStyle 로직을 보면 이미 모든 처리를 해주고 있기 때문에 그냥 쓰셔도 됩니다
```
public String getSimpleGroomingStyle() {
        if (type.isCleanGrooming()) {
            return type.getDescription();
        }
        String faceType = totalGroomingFaceType.getDescription();
        String bodyType = totalGroomingBodyType.getBaseStyleName();
        return faceType +  " + " + bodyType;
    }
```
만약 위생미용이면 "위생미용", 전체미용이면  `faceType +  " + " + bodyType;` 이렇게 말아서 주기 때문에 "알머리컷 + 가위컷"
이런 식으로 반환해요
근디 저 로직을 타면 위생미용일 시 null 을 리턴하는데, 그러면 안되겠죠? 위생미용도 화면에 보여주어야 하니까

as is: 
```
        String groomingStyle = (proposal.getTotalGroomingFaceType() != null && proposal.getTotalGroomingBodyType() != null)
                ? proposal.getSimpleGroomingStyle()
                : null;
```
to be: 
`String groomingStyle = proposal.getSimpleGroomingStyle()`

하시면 될 것 같습니다

2024-12-15 15:12 UTC, Shanate commented on peauty-persistence/src/main/java/com/peauty/persistence/review/ReviewMapper.java
> +                : null;
해당 부분 수정하고서 테스트에서 오류가 나길래 왜 오류가 나는가 싶었는데...groomingType을 보지 않고 있었네요.
Mapper 수정하니까 위진영님 말씀대로 위생미용일 때는 위생미용을, 전체미용일 때는 해당 미용 안에서 faceType과 bodyType을 잘 출력해주고있습니다.
늘 감사합니다

2024-12-15 15:14 UTC, Shanate commented on peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/GetDesignerReviewsResult.java
> +            String content
TODO로 돌려놓고 내일 중으로 수정하도록 하겠습니다.

2024-12-15 15:16 UTC, Shanate commented on peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/GetDesignerReviewsResult.java
> +            String totalGroomingFaceType,
제가 저 전체미용 안에서의 컷만 보고 있었네요.
만들어두신 groomingType을 전혀 인지하지 못 하고 있었습니다.
다음부터 피그마와 만들어둔 API를 신중하게 살펴보도록 하겠습니다.

2024-12-16 00:23 UTC, Shanate commented on peauty-customer-api/src/main/java/com/peauty/customer/business/review/dto/GetDesignerReviewsResult.java
> +            String content
수정했습니다. 이후 추가적인 API가 있을 수 있기 때문에 Response Body에 id를 내려줘야하는 것 상기해두고 있겠습니다.

2024-12-16 00:52 UTC, weejinyoung approved these changes
LGTM

2024-12-16 01:56 UTC, merged